### PR TITLE
Improve Makefile and build related files to enable builds on MacOS/Darwin

### PR DESCRIPTION
**Pull request by lervag**
This is still a WIP, but it is progressing.

@jabirali Feel free to test this and suggest improvements.

### CODE REVIEW

**Comment by lervag** [comment]
@morteham I'll let you know when this is ready for review.

**Comment by jabirali** [comment]
It does not build for me on macOS Catalina. Running `gmake optim` after cloning the repository and typing `gh pr checkout 1`:

```
gmake[2]: Entering directory '/Users/jabirali/Resilio/Code/work/thermopack/thermopack'
clang -cpp -fPIC -fdefault-real-8 -fdefault-double-8 -O3 -march=x86-64 -msse2 -funroll-loops -o./bin/thermopack_optim_gfortran_Darwin \
./objects/optim_gfortran_Darwin/thermopack.o ./bin/libthermopack_optim_gfortran_Darwin.a  -ldl -lstdc++ -llapack -lblas -lgfortran -lm
clang: warning: argument unused during compilation: '-cpp' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fdefault-real-8' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fdefault-double-8' [-Wunused-command-line-argument]
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0/../../../../../../x86_64-apple-darwin19/lib/x86_64-apple-darwin19/10.2.0/'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0/../../../../../../x86_64-apple-darwin19/lib/'
ld: warning: directory not found for option '-L/usr/local/Cellar/gcc/10.2.0/lib/gcc/10/gcc/x86_64-apple-darwin19/10.2.0/../../../x86_64-apple-darwin19/10.2.0/'
ld: warning: ignoring file ./bin/libthermopack_optim_gfortran_Darwin.a, building for macOS-x86_64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture x86_64:
  "___critical_MOD_calccriticaltv", referenced from:
      _MAIN__ in thermopack.o
  "___eoslibinit_MOD_init_saftvrmie", referenced from:
      _MAIN__ in thermopack.o
  "___eostv_MOD_pressure", referenced from:
      _MAIN__ in thermopack.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Makefile.code:228: run] Error 1
gmake[2]: Leaving directory '/Users/jabirali/Resilio/Code/work/thermopack/thermopack'
gmake[1]: *** [Makefile.code:221: thermopack] Error 2
gmake[1]: Leaving directory '/Users/jabirali/Resilio/Code/work/thermopack/thermopack'
gmake: *** [Makefile:188: optim_gfortran_Darwin] Error 2
```

However, @morteham previously shared a version of thermopack that *does* compile on macOS, except for (i) having to specify LIBRARY_PATH manually, and (ii) having to change compilation arguments to `-march=x86-64` in the Makefile. 

It seems like @morteham has resolved some compilation issues, and that his fixes have not been incorporated here yet?

**Comment by lervag** [comment]
I thought I had incorporated his fixes into this PR, including the `-march` option that should be correct. Did you do `gmake clean` first?

**Comment by jabirali** [comment]
> I thought I had incorporated his fixes into this PR, including the `-march` option that should be correct. Did you do `gmake clean` first?

The `-march` option is correct in your version – I meant that those were the two things that didn't work in his last version :)

Remembering to do a `gmake clean` first was a good tip; I had already done a new clean clone of the repo before trying your PR, so this branch was correct, but when comparing with @morteham's code that did compile I had forgotten to `gmake clean`. That kept me from discovering the real issue: that if you have GNU binutils installed (which I had reinstalled since last I tested the code), and have it in your `$PATH` before the usual system paths (as `brew` suggests you do when you install it), then the GNU versions of these tools are used and that breaks the compilation. 

I think we might want to add a quick note about this in the README; for compiling on macOS, if you have `binutils` installed, it is important that you don't have `/usr/local/opt/binutils/bin` before `/usr/bin` in your `$PATH` when compiling Thermopack. 

With this correction, and the `LIBRARY_PATH` update, your pull request compiles fine on my system :)

**Comment by lervag** [comment]
Strange. On MacOS, this line should be active:

https://github.com/SINTEF/thermopack/blob/d4eed4d125b3a1d9e75834b9277c4d775d78613c/Makefile.code#L30

Can you confirm that? As far as I can see, this is the same as in the version @morteham had.

**Comment by jabirali** [comment]
> Strange. On MacOS, this line should be active:
> 
> https://github.com/SINTEF/thermopack/blob/d4eed4d125b3a1d9e75834b9277c4d775d78613c/Makefile.code#L30
> 
> Can you confirm that? As far as I can see, this is the same as in the version @morteham had.

Your version of the `Makefile.code` does indeed contain this:
```
ifeq ($(UNAME),Darwin)
  LD = clang
  AR ?= /usr/bin/ar -r -c
else
  LD = $(FC)
  AR ?= /usr/bin/ar -rc -o
endif
```

However, line 197 contains:
```
$(AR) -rc -o $(BDIR)/libthermopack_$(TARGET).a $(OBJE) $(OBJIF)
```
The `-rc -o` should be removed here, since the arguments are contained in the `AR` definition. Just removing these arguments do however not work, and adding `@echo $(AR)` just prints `ar` without full path or arguments. Replacing line 197 with a hardcoded path like this, it suddenly compiles fine:
```
/usr/bin/ar -r -c $(BDIR)/libthermopack_$(TARGET).a $(OBJE) $(OBJIF)
```

I think the conclusion hwre is that the code setting `AR` does not work as intended; it does not include the full path to `ar` for some reason (causing the `ar` from `binutils` to override it when in path), and it does not include the `-r -c` arguments that are required. Any ideas why this might be the case? I am using GNU make here; does this work as intended on Linux?

Suggestion: if you remove `-rc -o` on line 197, and add a directory to the beginning of `$PATH` containing a test script called `ar`. Does the Makefile work as intended on Linux then, or might there be a bug in the Makefile?

**Comment by lervag** [comment]
Strange things. But I think I've fixed it now. Please test again.

**Comment by jabirali** [comment]
Good job, appears to build fine for me now, even with `binutils` installed and in the beginning of `$PATH`.

**Comment by lervag** [comment]
With that it seems we should be ready for merge. Let's wait until Geir and Morten has tested properly.

**Review by morteham — APPROVED** [review]
Makefiles are now working for Linux, MacOS and Windows using MSYS2/Mingw-w64

**Pull request merged**
