### PR TITLE
Added fluid file and mie-parameters for krypton

### PR DESCRIPTION
**Pull request by vegardjervell**

### CODE REVIEW

**Comment by morteham** [comment]
Hi Vegard!

Can you also generate a new compdatadb.f90 file using the addon/pyUtils/compdata.py script and and include it?

Regards,
Morten

**Comment by vegardjervell** [comment]
jada, fikser nå :)

**Comment by morteham** [comment]
Hi!

Is there are some unintentional LJF data in the new compdatadb.f90? Hide the new LJF json files, and they will not be included.

Regards,
Morten

**Comment by vegardjervell** [comment]
Oops, thats right, fixed now

**Review by morteham — APPROVED** [review]

**Comment by morteham** [comment]
Thanks, Vegard!

**Pull request merged**
